version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - browser-tools/install-chrome
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: echo 'done--'
            - run: git clone git@github.com:cirbuk/kubric-automation-testing.git
            - run: cd kubric-automation-testing/; ls ; npm install ; npm test
            - store_artifacts:
                path: kubric-automation-testing/mochawesome-report/


workflows:
    build-and-test:
      jobs:
        - build-and-test
