version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "Executing automation tests...."
      - run:
          name: cURL to automation tests pipeline
          command: |
            echo "Hey, ther1e"

workflows:
    build-and-test:
      jobs:
        - build-and-test
